openai-service:
  api-key: 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
  audio-model: whisper-1
  http-client:
    read-timeout: 3000
    connect-timeout: 3000
  urls:
    base-url: https://api.openai.com/v1
    create-transcription-url: /audio/transcriptions