openai-service:
  api-key: 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
  gpt-model: gpt-3.5-turbo
  audio-model: whisper-1
  http-client:
    read-timeout: 3000
    connect-timeout: 3000
  urls:
    base-url: https://api.openai.com/v1
    create-transcription-url: /audio/transcriptions